-- Engelsiz Club — Keşfet varsayılan anahtar kelimeler
-- Admin panelinden düzenlenebilir. Tekrar çalıştırmak güvenli (ON CONFLICT).

insert into public.kesfet_keywords (phrase, polarity, weight, category_hint, is_weak) values
  -- Pozitif: engellilik
  ('engelli', 'positive', 12, 'engellilik', false),
  ('engellilik', 'positive', 14, 'engellilik', false),
  ('özel gereksinim', 'positive', 14, 'engellilik', false),
  ('özel gereksinimli', 'positive', 14, 'engellilik', false),
  ('down sendrom', 'positive', 16, 'hastaliklar', false),
  ('otizm', 'positive', 16, 'hastaliklar', false),
  ('otizm spektrum', 'positive', 16, 'hastaliklar', false),
  ('serebral palsi', 'positive', 16, 'hastaliklar', false),
  ('spastik', 'positive', 10, 'hastaliklar', false),
  ('işitme kaybı', 'positive', 14, 'engellilik', false),
  ('görme engel', 'positive', 14, 'engellilik', false),
  ('körlük', 'positive', 10, 'engellilik', false),
  ('sağır', 'positive', 8, 'engellilik', false),
  ('tekerlekli sandalye', 'positive', 14, 'erisilebilirlik', false),
  ('protez', 'positive', 10, 'engellilik', false),
  ('ortez', 'positive', 10, 'engellilik', false),
  ('rehabilitasyon', 'positive', 12, 'saglik', false),
  ('fizyoterapi', 'positive', 12, 'saglik', false),
  ('ergoterapi', 'positive', 12, 'saglik', false),
  ('dil konuşma', 'positive', 12, 'egitim', false),
  ('konuşma terapisi', 'positive', 12, 'egitim', false),
  -- Haklar
  ('engelli maaşı', 'positive', 16, 'haklar', false),
  ('evde bakım', 'positive', 14, 'haklar', false),
  ('rapor', 'positive', 6, 'haklar', true),
  ('engelli kimlik', 'positive', 14, 'haklar', false),
  ('özürlü aylığı', 'positive', 14, 'haklar', false),
  ('sgk', 'positive', 8, 'haklar', true),
  ('çözer', 'positive', 10, 'haklar', false),
  ('erişilebilirlik', 'positive', 16, 'erisilebilirlik', false),
  ('rampa', 'positive', 10, 'erisilebilirlik', false),
  ('sesli betimleme', 'positive', 12, 'erisilebilirlik', false),
  ('işaret dili', 'positive', 14, 'erisilebilirlik', false),
  -- Eğitim / aile
  ('özel eğitim', 'positive', 16, 'egitim', false),
  ('bep', 'positive', 10, 'egitim', false),
  ('kaynaştırma', 'positive', 12, 'egitim', false),
  ('okul', 'positive', 4, 'egitim', true),
  ('aile', 'positive', 6, 'aile', true),
  ('anne baba', 'positive', 8, 'aile', false),
  ('bakım veren', 'positive', 10, 'aile', false),
  ('kardeş', 'positive', 6, 'aile', true),
  -- Sağlık / hastalık
  ('nadir hastalık', 'positive', 16, 'hastaliklar', false),
  ('epilepsi', 'positive', 12, 'hastaliklar', false),
  ('kas hastalığı', 'positive', 14, 'hastaliklar', false),
  ('dmd', 'positive', 12, 'hastaliklar', false),
  ('sma', 'positive', 14, 'hastaliklar', false),
  ('prematüre', 'positive', 12, 'hastaliklar', false),
  ('gelişim geriliği', 'positive', 14, 'hastaliklar', false),
  ('nörogelişim', 'positive', 12, 'hastaliklar', false),
  ('sağlık bakanlığı', 'positive', 8, 'saglik', false),
  ('doktor', 'positive', 4, 'saglik', true),
  ('terapi', 'positive', 8, 'saglik', false),
  -- Zayıf / güçlü negatif (eğlence — alakasız)
  ('gündem', 'negative', 6, '', true),
  ('magazin', 'negative', 14, '', false),
  ('unboxing', 'negative', 16, '', false),
  ('challenge', 'negative', 12, '', false),
  ('komedi', 'negative', 14, '', false),
  ('şarkı söyle', 'negative', 12, '', false),
  ('müzik klibi', 'negative', 14, '', false),
  ('gameplay', 'negative', 16, '', false),
  ('vlog', 'negative', 10, '', false),
  ('makyaj', 'negative', 14, '', false),
  ('futbol maç', 'negative', 14, '', false),
  ('prank', 'negative', 16, '', false),
  ('asmr', 'negative', 10, '', true),
  ('tiktok dans', 'negative', 16, '', false),
  ('eğlence videosu', 'negative', 14, '', false),
  -- Sağlık iddiası — asla otomatik onay
  ('kesin iyileştirir', 'safety', 20, '', false),
  ('mucize tedavi', 'safety', 20, '', false),
  ('doktora gerek yok', 'safety', 20, '', false),
  ('%100 tedavi', 'safety', 20, '', false),
  ('garantili şifa', 'safety', 20, '', false),
  ('ilaçsız kesin', 'safety', 16, '', false),
  ('bir günde iyileş', 'safety', 18, '', false),
  ('bitkisel kesin çözüm', 'safety', 16, '', false),
  ('kanseri yok eder', 'safety', 20, '', false),
  -- Haklar / rapor (TR ek)
  ('ötv muafiyet', 'positive', 16, 'haklar', false),
  ('engelli raporu', 'positive', 14, 'haklar', false),
  ('engelli aylığı', 'positive', 16, 'haklar', false),
  ('kaynaştırma eğitim', 'positive', 12, 'egitim', false),
  ('dehb', 'positive', 14, 'hastaliklar', false),
  ('disleksi', 'positive', 12, 'egitim', false),
  ('multipl skleroz', 'positive', 14, 'hastaliklar', false),
  ('spina bifida', 'positive', 16, 'hastaliklar', false),
  ('rett sendrom', 'positive', 14, 'hastaliklar', false),
  ('angelman', 'positive', 14, 'hastaliklar', false),
  ('duchenne', 'positive', 14, 'hastaliklar', false),
  ('işitme engel', 'positive', 14, 'engellilik', false),
  ('görme engelli', 'positive', 14, 'engellilik', false),
  -- English (Keşfet TR+EN)
  ('autism', 'positive', 16, 'hastaliklar', false),
  ('autistic', 'positive', 14, 'hastaliklar', false),
  ('down syndrome', 'positive', 16, 'hastaliklar', false),
  ('cerebral palsy', 'positive', 16, 'hastaliklar', false),
  ('wheelchair', 'positive', 14, 'erisilebilirlik', false),
  ('disability', 'positive', 12, 'engellilik', false),
  ('special education', 'positive', 16, 'egitim', false),
  ('special needs', 'positive', 14, 'engellilik', false),
  ('accessibility', 'positive', 16, 'erisilebilirlik', false),
  ('sign language', 'positive', 14, 'erisilebilirlik', false),
  ('physiotherapy', 'positive', 12, 'saglik', false),
  ('physical therapy', 'positive', 12, 'saglik', false),
  ('occupational therapy', 'positive', 12, 'saglik', false),
  ('speech therapy', 'positive', 12, 'egitim', false),
  ('spinal muscular atrophy', 'positive', 16, 'hastaliklar', false),
  ('muscular dystrophy', 'positive', 14, 'hastaliklar', false),
  ('rett syndrome', 'positive', 14, 'hastaliklar', false),
  ('angelman syndrome', 'positive', 14, 'hastaliklar', false),
  ('multiple sclerosis', 'positive', 14, 'hastaliklar', false),
  ('epilepsy', 'positive', 12, 'hastaliklar', false),
  ('adhd', 'positive', 12, 'hastaliklar', false),
  ('inclusive education', 'positive', 12, 'egitim', false),
  ('hearing loss', 'positive', 14, 'engellilik', false),
  ('visually impaired', 'positive', 14, 'engellilik', false),
  ('rare disease', 'positive', 16, 'hastaliklar', false),
  ('rehabilitation', 'positive', 12, 'saglik', false),
  ('caregiver', 'positive', 10, 'aile', false),
  ('dyslexia', 'positive', 12, 'egitim', false)
on conflict (phrase, polarity) do nothing;

notify pgrst, 'reload schema';
