-- Alakasız pending haberleri reddet (engelli/özel gereksinim çekirdeği yoksa).
-- SQL Editor → Run.
-- Collector JS süzgeci ile uyumlu tut: yalnız "engelli" yetmez; özel gereksinim,
-- özel eğitim, kaynaştırma, otizm, down, SMA, CVI vb. de çekirdek sayılır.
-- burs / İŞKUR / istihdam / rehabilitasyon / evde bakım TEK BAŞINA yeterli değil.

update public.useful_content
set
  status = 'rejected',
  ai_notes = 'alakasız_haber',
  updated_at = now()
where status = 'pending_review'
  and not (
       title ilike '%engell%'
    or summary ilike '%engell%'
    or title ilike '%engeli%'
    or summary ilike '%engeli%'
    or title ilike '%engelsiz%'
    or summary ilike '%engelsiz%'
    or title ilike '%özel gereksinim%'
    or summary ilike '%özel gereksinim%'
    or title ilike '%ozel gereksinim%'
    or summary ilike '%ozel gereksinim%'
    or title ilike '%özel eğitim%'
    or summary ilike '%özel eğitim%'
    or title ilike '%ozel egitim%'
    or summary ilike '%ozel egitim%'
    or title ilike '%özel yetenek%'
    or summary ilike '%özel yetenek%'
    or title ilike '%ozel yetenek%'
    or summary ilike '%ozel yetenek%'
    or title ilike '%kaynaştırma%'
    or summary ilike '%kaynaştırma%'
    or title ilike '%kaynastirma%'
    or summary ilike '%kaynastirma%'
    or title ilike '%bireyselleştirilmiş eğitim%'
    or summary ilike '%bireyselleştirilmiş eğitim%'
    or title ilike '%destek eğitim odası%'
    or summary ilike '%destek eğitim odası%'
    or title ilike '%destek egitim odasi%'
    or summary ilike '%destek egitim odasi%'
    or title ilike '%otizm%'
    or summary ilike '%otizm%'
    or title ilike '%asperger%'
    or summary ilike '%asperger%'
    or title ilike '%otizm spektrum%'
    or summary ilike '%otizm spektrum%'
    or title ilike '%osb''li%'
    or summary ilike '%osb''li%'
    or title ilike '%osb’li%'
    or summary ilike '%osb’li%'
    or title ilike '%down sendrom%'
    or summary ilike '%down sendrom%'
    or title ilike '%down syndrome%'
    or summary ilike '%down syndrome%'
    or title ilike '%mongolizm%'
    or summary ilike '%mongolizm%'
    or title ilike '%trizomi 21%'
    or summary ilike '%trizomi 21%'
    or title ilike '%trisomi 21%'
    or summary ilike '%trisomi 21%'
    or title ilike '%trisomy 21%'
    or summary ilike '%trisomy 21%'
    or title ilike '%serebral pal%'
    or summary ilike '%serebral pal%'
    or title ilike '%serebral palsi%'
    or summary ilike '%serebral palsi%'
    or title ilike '%serebral paldi%'
    or summary ilike '%serebral paldi%'
    or title ilike '%cerebral palsy%'
    or summary ilike '%cerebral palsy%'
    or title ilike '%sp''li%'
    or summary ilike '%sp''li%'
    or title ilike '%sp’li%'
    or summary ilike '%sp’li%'
    or title ~* '\mspli\M'
    or summary ~* '\mspli\M'
    or title ilike '%erişilebilir%'
    or summary ilike '%erişilebilir%'
    or title ilike '%erisilebilir%'
    or summary ilike '%erisilebilir%'
    or title ilike '%evde eğitim%'
    or summary ilike '%evde eğitim%'
    or title ilike '%evde egitim%'
    or summary ilike '%evde egitim%'
    or title ilike '%bakım aylığı%'
    or summary ilike '%bakım aylığı%'
    or title ilike '%bakim ayligi%'
    or summary ilike '%bakim ayligi%'
    or title ilike '%ötv%'
    or summary ilike '%ötv%'
    or title ilike '%otv muaf%'
    or summary ilike '%otv muaf%'
    or title ilike '%rehberlik araştırma%'
    or summary ilike '%rehberlik araştırma%'
    or title ilike '%rehberlik arastirma%'
    or summary ilike '%rehberlik arastirma%'
    or title ilike '%işitme engel%'
    or summary ilike '%işitme engel%'
    or title ilike '%isitme engel%'
    or summary ilike '%isitme engel%'
    or title ilike '%görme engel%'
    or summary ilike '%görme engel%'
    or title ilike '%gorme engel%'
    or summary ilike '%gorme engel%'
    or title ilike '%bedensel engel%'
    or summary ilike '%bedensel engel%'
    or title ilike '%zihinsel engel%'
    or summary ilike '%zihinsel engel%'
    or title ilike '%bedensel yetersiz%'
    or summary ilike '%bedensel yetersiz%'
    or title ilike '%zihinsel yetersiz%'
    or summary ilike '%zihinsel yetersiz%'
    or title ilike '%gelişim gerili%'
    or summary ilike '%gelişim gerili%'
    or title ilike '%gelisim gerili%'
    or summary ilike '%gelisim gerili%'
    or title ilike '%dil konuşma%'
    or summary ilike '%dil konuşma%'
    or title ilike '%dil konusma%'
    or summary ilike '%dil konusma%'
    or title ilike '%dil ve konuşma%'
    or summary ilike '%dil ve konuşma%'
    or title ilike '%tekerlekli sandalye%'
    or summary ilike '%tekerlekli sandalye%'
    or title ilike '%nadir hastalık%'
    or summary ilike '%nadir hastalık%'
    or title ilike '%nadir hastalik%'
    or summary ilike '%nadir hastalik%'
    or title ilike '%çözger%'
    or summary ilike '%çözger%'
    or title ilike '%cozger%'
    or summary ilike '%cozger%'
    or title ilike '%erözger%'
    or summary ilike '%erözger%'
    or title ilike '%erozger%'
    or summary ilike '%erozger%'
    or title ilike '%işaret dili%'
    or summary ilike '%işaret dili%'
    or title ilike '%isaret dili%'
    or summary ilike '%isaret dili%'
    or title ilike '%ekpss%'
    or summary ilike '%ekpss%'
    or title ilike '%korumalı işyeri%'
    or summary ilike '%korumalı işyeri%'
    or title ilike '%korumali isyeri%'
    or summary ilike '%korumali isyeri%'
    or title ilike '%işitme yetersiz%'
    or summary ilike '%işitme yetersiz%'
    or title ilike '%görme yetersiz%'
    or summary ilike '%görme yetersiz%'
    or title ilike '%protez ortez%'
    or summary ilike '%protez ortez%'
    or title ilike '%disleksi%'
    or summary ilike '%disleksi%'
    or title ilike '%braille%'
    or summary ilike '%braille%'
    or title ilike '%paralimpik%'
    or summary ilike '%paralimpik%'
    or title ilike '%özürlü%'
    or summary ilike '%özürlü%'
    or title ilike '%ozurlu%'
    or summary ilike '%ozurlu%'
    or title ~* '\m(sma|dehb|adhd|cvi|bep|oyc|orgm)\M'
    or summary ~* '\m(sma|dehb|adhd|cvi|bep|oyc|orgm)\M'
  );

-- Genel belediye RSS (Bursa BB) engelli odaklı değil.
update public.content_sources
set is_active = false,
    notes = 'genel haber; engelli süzgeci için kapatıldı',
    updated_at = now()
where url ilike '%bursa.bel.tr%';
