/** Merkezi gazete / ajans RSS listesi. HTML tarama yok. */
export const NEWS_SOURCES = [
  {
    source_name: 'Hürriyet',
    source_url: 'https://www.hurriyet.com.tr',
    rss_url: 'https://www.hurriyet.com.tr/rss/gundem',
    search_url: '',
    enabled: true,
  },
  {
    source_name: 'Milliyet',
    source_url: 'https://www.milliyet.com.tr',
    rss_url: 'https://www.milliyet.com.tr/rss/rssNew/gundemRss.xml',
    search_url: '',
    enabled: true,
  },
  {
    source_name: 'Sabah',
    source_url: 'https://www.sabah.com.tr',
    rss_url: 'https://www.sabah.com.tr/rss/gundem.xml',
    search_url: '',
    enabled: true,
  },
  {
    source_name: 'Sözcü',
    source_url: 'https://www.sozcu.com.tr',
    rss_url: 'https://www.sozcu.com.tr/feed/',
    search_url: '',
    enabled: true,
  },
  {
    source_name: 'Habertürk',
    source_url: 'https://www.haberturk.com',
    rss_url: 'https://www.haberturk.com/rss',
    search_url: '',
    enabled: true,
  },
  {
    source_name: 'CNN Türk',
    source_url: 'https://www.cnnturk.com',
    rss_url: 'https://www.cnnturk.com/feed/rss/all/news',
    search_url: '',
    enabled: true,
  },
  {
    source_name: 'NTV',
    source_url: 'https://www.ntv.com.tr',
    rss_url: 'https://www.ntv.com.tr/gundem.rss',
    search_url: '',
    enabled: true,
  },
  {
    source_name: 'TRT Haber',
    source_url: 'https://www.trthaber.com',
    rss_url: 'https://www.trthaber.com/sondakika.rss',
    search_url: '',
    enabled: true,
  },
  {
    source_name: 'Anadolu Ajansı',
    source_url: 'https://www.aa.com.tr',
    rss_url: 'https://www.aa.com.tr/tr/rss/default?cat=guncel',
    search_url: '',
    enabled: true,
  },
  {
    source_name: 'DHA',
    source_url: 'https://www.dha.com.tr',
    rss_url: 'https://www.dha.com.tr/rss',
    search_url: '',
    enabled: true,
  },
  {
    source_name: 'Türkiye Gazetesi',
    source_url: 'https://www.turkiyegazetesi.com.tr',
    rss_url: 'https://www.turkiyegazetesi.com.tr/rss/rss.xml',
    search_url: '',
    enabled: true,
  },
  {
    source_name: 'Yeni Şafak',
    source_url: 'https://www.yenisafak.com',
    rss_url: 'https://www.yenisafak.com/rss',
    search_url: '',
    enabled: true,
  },
  {
    source_name: 'Karar',
    source_url: 'https://www.karar.com',
    rss_url: 'https://www.karar.com/rss',
    search_url: '',
    enabled: true,
  },
  {
    source_name: 'Cumhuriyet',
    source_url: 'https://www.cumhuriyet.com.tr',
    rss_url: 'https://www.cumhuriyet.com.tr/rss/son_dakika.xml',
    search_url: '',
    enabled: true,
  },
  {
    source_name: 'BirGün',
    source_url: 'https://www.birgun.net',
    rss_url: 'https://www.birgun.net/rss',
    search_url: '',
    enabled: true,
  },
  {
    source_name: 'T24',
    source_url: 'https://t24.com.tr',
    rss_url: 'https://t24.com.tr/rss',
    search_url: '',
    enabled: true,
  },
  {
    source_name: 'Gazete Duvar',
    source_url: 'https://www.gazeteduvar.com.tr',
    rss_url: 'https://www.gazeteduvar.com.tr/export/rss',
    search_url: '',
    enabled: true,
  },
  {
    source_name: 'Odatv',
    source_url: 'https://www.odatv.com',
    rss_url: 'https://www.odatv.com/rss.xml',
    search_url: '',
    enabled: true,
  },
  {
    source_name: 'Ensonhaber',
    source_url: 'https://www.ensonhaber.com',
    rss_url: 'https://www.ensonhaber.com/rss.xml',
    search_url: '',
    enabled: true,
  },
];

export function enabledSources() {
  return NEWS_SOURCES.filter((s) => s.enabled && s.rss_url);
}
